server:
  port: 4545

spring:
  application:
    name: WigellGateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: WigellRepairs
              uri: http://localhost:5555
              predicates:
                - Path=/api/wigellrepairs/**

            - id: WigellRepairsCurrencyConverter
              uri: http://localhost:8081
              predicates:
                - Path=/convert/sekToEuro/**
